version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: software-catalog-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: software-catalog-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/software_catalog
      - JWT_SECRET=your-secret-key
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: software-catalog-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=software_catalog
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    container_name: software-catalog-storage
    volumes:
      - storage_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  storage_data: 