version: '3.8'

services:
  backend:
    build: ./backend
    container_name: software-catalog-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - software_uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/software-catalog
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: software-catalog-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: software-catalog-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  software_uploads:
